### ISSUE TITLE
Missing Parentheses in Call to 'print'

### ISSUE THREAD

**Issue by rubenkr** [markus-perl/pushover-cli#3]
Hi !

first of all thank you very much for this great pushover integration. I am struggling to get it to life. Following your README I adapted the /etc/pushover-cli.conf. But when executing pushover-cli it throws the following error:

`➜  ~ pushover-cli "test" "title"
  File "/usr/bin/pushover-cli", line 34
    print message
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(message)?`

Do you know what this could be? I am using following architecture:

`Python version
>>> print (sys.version)
3.8.2 (default, Feb 26 2020, 22:21:03) 
`
`➜  ~ uname -a
Linux T450 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux
`

May it be that only Python2 can be used? How to change pushover-cli to python2 without messing up the whole system?

Thank you very much !

**Comment by markus-perl** [comment]
Hi, the script was initially developed for python 2.7. I've not tested the script yet with python 3 but I think it should run with a few changes. Feel free to submit a pull request.

**Comment by markus-perl** [comment]
Fiexed.
