### ISSUE TITLE
Piping to std-in of pushover-cli sends multiple messages for multiple lines

### ISSUE THREAD

**Issue by jamesbiederbeck** [markus-perl/pushover-cli#5]
Pipe some multiline output into pushover-cli, and it will send each line as its own message.
Is there a way to batch these? I would have expected it to wait for an EOF.

**Comment by markus-perl** [comment]
Hi James, this is the expected behavior. I developed the stdin feature initially to pipe errors from a log file to my phone: tail -f /var/log/my.log | pushover-cli -
